INSERT INTO blog_posts (
  slug, title, excerpt, cover_image_url, content_markdown, content_html, content_blocks,
  status, language, reading_time_minutes, published_at, seo_title, seo_description
)
VALUES
(
  'welcome-to-my-blog',
  'Welcome to my blog',
  'A short introduction to the blog format, what will live here, and how the editor works.',
  '/assets/blog/welcome-mascot.png',
  '# Welcome to my blog\n\nThis blog is where I publish technical notes, case studies, and project write-ups.',
  '<h2>Welcome to my blog</h2><p>This blog is where I publish technical notes, case studies, and project write-ups.</p>',
  '[
    {"id":"welcome-1","type":"heading","data":{"level":2,"text":"Welcome to my blog"}},
    {"id":"welcome-2","type":"paragraph","data":{"text":"This space collects project notes, engineering decisions, and research summaries. It is written as a living notebook, so articles can mix prose, images, code, and outputs in one place."}},
    {"id":"welcome-2b","type":"paragraph","data":{"text":"The structure of each article follows a paper-like flow: context, method, evidence, implementation detail, and a short reflection on what I would improve next."}},
    {"id":"welcome-3","type":"quote","data":{"text":"A good blog is a changelog for ideas.","cite":"Nguyen Nhat Bang"}},
    {"id":"welcome-4","type":"image","data":{"url":"/assets/blog/welcome-mascot.png","alt":"Portfolio mascot","caption":"The mascot that anchors the portfolio identity."}},
    {"id":"welcome-5","type":"paragraph","data":{"text":"In the next posts I will share two capstone-style case studies: a stroke risk prediction pipeline and a lung cancer classification system. Both posts pull directly from the project folders inside this repo."}},
    {"id":"welcome-6","type":"link","data":{"label":"Browse the public blog","url":"/blog"}}
  ]'::jsonb,
  'published',
  'en',
  2,
  NOW(),
  'Welcome to my blog',
  'An introduction to the portfolio blog and what will be published here.'
)
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title,
    excerpt = EXCLUDED.excerpt,
    cover_image_url = EXCLUDED.cover_image_url,
    content_markdown = EXCLUDED.content_markdown,
    content_html = EXCLUDED.content_html,
    content_blocks = EXCLUDED.content_blocks,
    status = EXCLUDED.status,
    language = EXCLUDED.language,
    reading_time_minutes = EXCLUDED.reading_time_minutes,
    published_at = EXCLUDED.published_at,
    seo_title = EXCLUDED.seo_title,
    seo_description = EXCLUDED.seo_description,
    updated_at = NOW();

INSERT INTO blog_posts (
  slug, title, excerpt, cover_image_url, content_markdown, content_html, content_blocks,
  status, language, reading_time_minutes, published_at, seo_title, seo_description
)
VALUES
(
  'healthcare-stroke-prediction',
  'Healthcare Stroke Prediction',
  'A patient-level stroke risk pipeline with deduplication, SHAP analysis, and synthetic energy expenditure features.',
  '/assets/blog/stroke-roc-curves.png',
  '# Healthcare Stroke Prediction\n\nThis project merges clinical data, feature synthesis, and threshold-aware classification.',
  '<h2>Healthcare Stroke Prediction</h2><p>This project merges clinical data, feature synthesis, and threshold-aware classification.</p>',
  '[
    {"id":"stroke-1","type":"heading","data":{"level":2,"text":"I. INTRODUCTION"}},
    {"id":"stroke-2","type":"paragraph","data":{"text":"Stroke prediction is a high-stakes classification problem because false negatives can delay care while false positives can overload triage workflows. The paper focuses on making the evaluation patient-level rather than row-level, which is the right way to avoid leakage in a repeated-visit dataset."}},
    {"id":"stroke-2b","type":"paragraph","data":{"text":"The broader goal is not to maximize a single score in isolation, but to build a screening pipeline that can be interpreted, tuned, and deployed responsibly. That is why the article combines classical classifiers, threshold selection, and SHAP analysis in one flow."}},
    {"id":"stroke-3","type":"heading","data":{"level":2,"text":"II. RELATED WORK"}},
    {"id":"stroke-3b","type":"paragraph","data":{"text":"Previous stroke studies often report strong metrics on row-level splits, but the numbers can collapse once patient identity is respected. This project intentionally follows a stricter protocol so that performance reflects actual generalization rather than memorization of repeated encounters."}},
    {"id":"stroke-4","type":"heading","data":{"level":2,"text":"III. MATERIALS AND METHODS"}},
    {"id":"stroke-4a","type":"heading","data":{"level":3,"text":"A. Dataset Description"}},
    {"id":"stroke-4b","type":"paragraph","data":{"text":"The raw table contains 143,960 visit rows that are collapsed into 5,110 unique patient profiles. Key clinical variables include age, blood pressure, cholesterol, glucose, body size, and self-reported lifestyle indicators."}},
    {"id":"stroke-4c","type":"heading","data":{"level":3,"text":"B. Patient-Level Deduplication"}},
    {"id":"stroke-4d","type":"paragraph","data":{"text":"Deduplication is performed before any split so that a patient never appears in both training and testing partitions. This step removes leakage from repeated rows and makes the evaluation meaningful."}},
    {"id":"stroke-4e","type":"heading","data":{"level":3,"text":"C. Stratified Patient-Level Split"}},
    {"id":"stroke-4f","type":"paragraph","data":{"text":"The split is stratified to preserve the class balance across train, validation, and test sets. Threshold tuning is done on validation data only, then locked before final reporting."}},
    {"id":"stroke-4g","type":"heading","data":{"level":3,"text":"D. Synthetic Energy Expenditure Estimation"}},
    {"id":"stroke-4h","type":"paragraph","data":{"text":"A separate exercise regression task estimates calories burned and converts that output into a behavioral proxy. The synthetic feature is used to enrich the feature space without pretending to replace a measured clinical signal."}},
    {"id":"stroke-4i","type":"heading","data":{"level":3,"text":"E. Feature Selection and Anomaly Analysis"}},
    {"id":"stroke-4j","type":"paragraph","data":{"text":"Feature importance and correlation checks are used to identify noisy or suspicious variables. The analysis also highlights where some engineered measurements behave differently from the rest of the cohort."}},
    {"id":"stroke-4k","type":"heading","data":{"level":3,"text":"F. Classification Models"}},
    {"id":"stroke-4l","type":"paragraph","data":{"text":"Several classical models are compared, including Logistic Regression, Random Forest, Extra Trees, Gradient Boosting, Histogram Gradient Boosting, and XGBoost. This keeps the experiment reproducible and easy to benchmark."}},
    {"id":"stroke-4m","type":"heading","data":{"level":3,"text":"G. Decision Threshold Optimization"}},
    {"id":"stroke-4n","type":"paragraph","data":{"text":"Because the dataset is imbalanced, threshold choice matters as much as classifier choice. Validation-set threshold tuning is used to balance recall, precision, and the downstream screening objective."}},
    {"id":"stroke-5","type":"heading","data":{"level":2,"text":"IV. EXPERIMENTAL RESULTS"}},
    {"id":"stroke-5a","type":"heading","data":{"level":3,"text":"A. Experimental Setup"}},
    {"id":"stroke-5b","type":"paragraph","data":{"text":"The evaluation protocol reports accuracy, precision, recall, F1, and AUC under a fixed held-out patient test set. The reported numbers are intentionally paired with threshold values so the operating point is explicit."}},
    {"id":"stroke-5c","type":"heading","data":{"level":3,"text":"B. Calorie Regressor Performance"}},
    {"id":"stroke-5d","type":"paragraph","data":{"text":"The separate calorie regressor provides the synthetic energy feature used in the stroke model. Its role is auxiliary, but it helps demonstrate how a behavioral signal can be attached to a clinical classifier."}},
    {"id":"stroke-5e","type":"heading","data":{"level":3,"text":"C. Stroke Classifier Comparison"}},
    {"id":"stroke-5f","type":"paragraph","data":{"text":"Gradient Boosting gives the strongest F1 at its chosen threshold, while XGBoost gives the strongest ranking quality and recall. That is why the final paper distinguishes between screening-oriented and balanced operating points."}},
    {"id":"stroke-img-1","type":"image","data":{"url":"/assets/blog/stroke-confusion-matrix.png","alt":"Stroke confusion matrix","caption":"Confusion matrix on the held-out patient test set."}},
    {"id":"stroke-img-2","type":"image","data":{"url":"/assets/blog/stroke-roc-curves.png","alt":"ROC curves for stroke models","caption":"ROC curves for six classifiers, with XGBoost selected as the best performer."}},
    {"id":"stroke-5g","type":"heading","data":{"level":3,"text":"D. ROC Curve Analysis"}},
    {"id":"stroke-5h","type":"paragraph","data":{"text":"The ROC curves show that the class imbalance does not prevent useful separation when thresholding is handled carefully. XGBoost is selected because it balances recall and ranking performance better than the other candidates."}},
    {"id":"stroke-5i","type":"heading","data":{"level":3,"text":"E. SHAP Feature Importance"}},
    {"id":"stroke-5j","type":"paragraph","data":{"text":"SHAP ranks age and average glucose among the strongest contributors, which is consistent with common stroke risk intuition. This section is important because it translates a black-box score into a human-readable explanation."}},
    {"id":"stroke-5k","type":"heading","data":{"level":3,"text":"G. Anomalous Feature Diagnostics"}},
    {"id":"stroke-5l","type":"paragraph","data":{"text":"Pearson correlation and ablation tests expose where certain engineered variables behave oddly. Those diagnostics are useful because they prevent the project from overclaiming the value of a noisy feature."}},
    {"id":"stroke-table-1","type":"table","data":{"title":"Table I. Classifier performance on the deduplicated test set","headers":["Model","Thresh.","Acc.","Prec.","Recall","F1","AUC"],"rows":[["Grad. Boost.","0.080","83.6%","19.0%","71.1%","0.300","0.857"],["Log. Reg.","0.605","81.2%","17.7%","76.3%","0.287","0.859"],["XGBoost","0.585","79.5%","17.1%","81.6%","0.283","0.863"],["Rand. Forest","0.570","81.7%","17.3%","71.1%","0.278","0.853"],["Extra Trees","0.570","80.3%","17.0%","76.3%","0.278","0.848"],["Hist. GB","0.655","84.4%","16.9%","55.3%","0.259","0.858"]]}},
    {"id":"stroke-img-3","type":"image","data":{"url":"/assets/blog/stroke-shap-bar.png","alt":"SHAP summary bar chart","caption":"SHAP feature importance summary."}},
    {"id":"stroke-img-4","type":"image","data":{"url":"/assets/blog/stroke-shap-beeswarm.png","alt":"SHAP beeswarm plot","caption":"SHAP directionality check on the final feature set."}},
    {"id":"stroke-table-2","type":"table","data":{"title":"Table II. Anomalous feature Pearson correlations with stroke_target","headers":["Feature","r (Pearson)","Mean (No stroke)","Mean (Stroke)"],"rows":[["avg_ap_hi","-0.030","126.35","124.59"],["avg_ap_lo","-0.030","97.29","86.46"],["heart_cholesterol","-0.045","218.79","207.12"],["bmi (raw)","-0.052","27.87","25.58"]]}},
    {"id":"stroke-table-3","type":"table","data":{"title":"Table III. Feature ablation study","headers":["Feature Variant","Accuracy","F1","AUC-ROC"],"rows":[["All features","93.4%","0.243","0.740"],["Drop avg_weight, avg_height","93.4%","0.243","0.740"],["Drop bmi, keep wt/ht","91.4%","0.212","0.695"],["Drop body size, keep bmi","93.7%","0.133","0.732"]]}},
    {"id":"stroke-7","type":"code","data":{"language":"bash","code":"python Code/Model.py\\npython Code/compare_models.py\\npython Code/evaluate_model.py\\npython Code/generate_figures.py"}},
    {"id":"stroke-8","type":"heading","data":{"level":2,"text":"V. DISCUSSION"}},
    {"id":"stroke-8c","type":"paragraph","data":{"text":"The discussion frames the result as a threshold and evaluation problem more than a model-selection problem. The paper is deliberately conservative: it prefers a reproducible patient-level protocol over an overly optimistic row-level benchmark."}},
    {"id":"stroke-8d","type":"paragraph","data":{"text":"That is also why the feature diagnostics matter. They show where the data is stable, where it is noisy, and which signals should be treated as supporting evidence instead of primary evidence."}},
    {"id":"stroke-9","type":"heading","data":{"level":2,"text":"VI. C++ DEPLOYMENT PIPELINE"}},
    {"id":"stroke-9b","type":"paragraph","data":{"text":"The deployment path packages the feature engineering steps and model inference into a reproducible pipeline. That makes the work useful beyond a notebook, especially for edge or low-dependency environments."}},
    {"id":"stroke-10","type":"heading","data":{"level":2,"text":"VII. CONCLUSION"}},
    {"id":"stroke-10b","type":"quote","data":{"text":"XGBoost achieved the highest AUC-ROC of 0.8630 and recall of 81.58% on the held-out patient test set.","cite":"Final paper"}}
  ]'::jsonb,
  'published',
  'en',
  8,
  NOW(),
  'Healthcare Stroke Prediction',
  'A technical case study on stroke risk prediction with deduplication and SHAP.'
)
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title,
    excerpt = EXCLUDED.excerpt,
    cover_image_url = EXCLUDED.cover_image_url,
    content_markdown = EXCLUDED.content_markdown,
    content_html = EXCLUDED.content_html,
    content_blocks = EXCLUDED.content_blocks,
    status = EXCLUDED.status,
    language = EXCLUDED.language,
    reading_time_minutes = EXCLUDED.reading_time_minutes,
    published_at = EXCLUDED.published_at,
    seo_title = EXCLUDED.seo_title,
    seo_description = EXCLUDED.seo_description,
    updated_at = NOW();

INSERT INTO blog_posts (
  slug, title, excerpt, cover_image_url, content_markdown, content_html, content_blocks,
  status, language, reading_time_minutes, published_at, seo_title, seo_description
)
VALUES
(
  'lung-cancer-aff-cpp-inference',
  'Lung Cancer AFF + C++ Inference',
  'A hybrid CT classification system that fuses deep features, handcrafted texture descriptors, and ONNX Runtime C++ deployment.',
  '/assets/blog/lung-fig-architecture.png',
  '# Lung Cancer AFF + C++ Inference\n\nThis project blends explainable image features with edge deployment.',
  '<h2>Lung Cancer AFF + C++ Inference</h2><p>This project blends explainable image features with edge deployment.</p>',
  '[
    {"id":"lung-1","type":"heading","data":{"level":2,"text":"I. INTRODUCTION"}},
    {"id":"lung-2","type":"paragraph","data":{"text":"Lung cancer classification from CT images benefits from both deep visual features and handcrafted texture descriptors. The paper argues that a hybrid pipeline is stronger than a pure CNN when the goal is not only accuracy, but also interpretability and edge deployment."}},
    {"id":"lung-2b","type":"paragraph","data":{"text":"The work is built around a practical constraint: the final system should be explainable to a clinician and exportable to a C++ runtime. That is why the article tracks both model performance and deployment fidelity."}},
    {"id":"lung-3","type":"heading","data":{"level":2,"text":"II. RELATED WORK"}},
    {"id":"lung-3b","type":"paragraph","data":{"text":"Prior CNN-based approaches reach high accuracy on CT datasets, but they usually do not explain which visual patterns matter and they often stop at Python inference. This paper combines deep transfer learning, handcrafted texture statistics, and an explicit edge runtime to close that gap."}},
    {"id":"lung-4","type":"heading","data":{"level":2,"text":"III. PROPOSED METHODOLOGY"}},
    {"id":"lung-4a","type":"heading","data":{"level":3,"text":"A. Image Preprocessing"}},
    {"id":"lung-4b","type":"paragraph","data":{"text":"Each CT image is converted to grayscale, resized, denoised, and normalized before feature extraction. The adaptive denoising step is designed to preserve contour detail while suppressing background noise."}},
    {"id":"lung-4c","type":"heading","data":{"level":3,"text":"B. Handcrafted Texture Feature Extraction"}},
    {"id":"lung-4d","type":"paragraph","data":{"text":"GLCM and LBP capture complementary local structure cues. These descriptors make the model more robust to texture differences that a deep backbone may not always emphasize on its own."}},
    {"id":"lung-4e","type":"heading","data":{"level":3,"text":"C. Deep Feature Extraction with MSCA"}},
    {"id":"lung-4f","type":"paragraph","data":{"text":"An InceptionV3 branch extracts semantic features from resized RGB input. The paper uses the mixed7 layer as a compact deep representation before fusion."}},
    {"id":"lung-4g","type":"heading","data":{"level":3,"text":"D. Attentional Feature Fusion (AFF)"}},
    {"id":"lung-4h","type":"paragraph","data":{"text":"AFF learns how much to trust the deep branch and the handcrafted branch for each sample. The point is not to concatenate everything blindly, but to make the fusion adaptive and data-dependent."}},
    {"id":"lung-4i","type":"heading","data":{"level":3,"text":"E. Classification and Explainability"}},
    {"id":"lung-4j","type":"paragraph","data":{"text":"The fused vector is passed into an MLP classifier, and explanation outputs are derived from the learned representation. The article pairs performance tables with class-level metrics so the reader can inspect the model beyond a single aggregate score."}},
    {"id":"lung-4k","type":"heading","data":{"level":3,"text":"F. Edge Deployment via C++ ONNX Runtime"}},
    {"id":"lung-4l","type":"paragraph","data":{"text":"The full preprocessing and inference pipeline is exported to ONNX and replayed in C++ using ONNX Runtime and OpenCV. This step validates that the research model can survive outside the Python notebook without changing the prediction behavior."}},
    {"id":"lung-img-1","type":"image","data":{"url":"/assets/blog/lung-fig-architecture.png","alt":"Hybrid architecture","caption":"Overall architecture of the hybrid explainable lung cancer framework."}},
    {"id":"lung-img-2","type":"image","data":{"url":"/assets/blog/lung-test-ct.png","alt":"Test CT input","caption":"Example CT input used by the C++ inference demo."}},
    {"id":"lung-img-3","type":"image","data":{"url":"/assets/blog/lung-confusion-matrix.png","alt":"Lung cancer confusion matrix","caption":"Cross-validation confusion matrix from the paper."}},
    {"id":"lung-img-4","type":"image","data":{"url":"/assets/blog/lung-roc-curves.png","alt":"Lung cancer ROC curves","caption":"ROC curves for the three-class classifier."}},
    {"id":"lung-img-5","type":"image","data":{"url":"/assets/blog/lung-ext-prediction.png","alt":"External prediction distribution","caption":"External dataset prediction distribution for robustness checks."}},
    {"id":"lung-5","type":"heading","data":{"level":2,"text":"IV. EXPERIMENTAL RESULTS"}},
    {"id":"lung-5a","type":"heading","data":{"level":3,"text":"A. Dataset and Experimental Setup"}},
    {"id":"lung-5b","type":"paragraph","data":{"text":"The IQ-OTHNCCD dataset contains 1,097 CT images across benign, malignant, and normal classes. The evaluation reports cross-validation metrics, class balance, and deployment validation so the experimental section reads like a paper rather than a demo log."}},
    {"id":"lung-5c","type":"heading","data":{"level":3,"text":"B. Classification Performance"}},
    {"id":"lung-5d","type":"paragraph","data":{"text":"The proposed hybrid system achieves strong weighted precision, recall, and F1 across folds. The result is important because it shows that the fused representation is stable and not overly dependent on a single class."}},
    {"id":"lung-5e","type":"heading","data":{"level":3,"text":"C. Comparison with Existing Methods"}},
    {"id":"lung-5f","type":"paragraph","data":{"text":"The paper positions the hybrid AFF approach against prior CT classification methods and argues that the fusion design improves both performance and interpretability. This is the main evidence that the added handcrafted branch is worth keeping."}},
    {"id":"lung-5g","type":"heading","data":{"level":3,"text":"D. Preprocessing Analysis"}},
    {"id":"lung-5h","type":"paragraph","data":{"text":"The denoising example shows that the preprocessing step reduces noise without erasing lesion boundaries. That matters because the handcrafted descriptors are sensitive to local texture and edge structure."}},
    {"id":"lung-5i","type":"heading","data":{"level":3,"text":"E. External Generalizability Evaluation"}},
    {"id":"lung-5j","type":"paragraph","data":{"text":"An external dataset is used to check whether the model generalizes beyond the source distribution. This section is the paper's answer to the usual criticism that medical models only work on one dataset."}},
    {"id":"lung-5k","type":"heading","data":{"level":3,"text":"F. Edge Deployment Validation"}},
    {"id":"lung-5l","type":"paragraph","data":{"text":"The C++ runtime is validated against the Python implementation to confirm feature parity and consistent outputs. The deployment story is as important as the classifier accuracy because the goal is practical portability."}},
    {"id":"lung-table-1","type":"table","data":{"title":"Table I. IQ-OTHNCCD dataset statistics","headers":["Class","Number of Images","Percentage"],"rows":[["Benign","120","10.94%"],["Malignant","561","51.14%"],["Normal","416","37.92%"],["Total","1,097","100.00%"]]}},
    {"id":"lung-table-2","type":"table","data":{"title":"Table II. Per-class validation metrics (5-fold CV)","headers":["Class","Precision","Recall","F1-Score","Support"],"rows":[["Benign","0.9735","0.9167","0.9442","120"],["Malignant","0.9947","0.9947","0.9947","561"],["Normal","0.9716","0.9880","0.9797","416"],["Weighted Avg","0.9841","0.9836","0.9835","1,097"]]}},
    {"id":"lung-table-3","type":"table","data":{"title":"Table III. Comparison with existing methods","headers":["Method","Dataset","Accuracy (%)","AUC"],"rows":[["VGG16 + SVM [17]","IQ-OTHNCCD","94.50","0.9520"],["ResNet50 [18]","IQ-OTHNCCD","96.20","0.9710"],["DenseNet121 [18]","IQ-OTHNCCD","95.80","0.9680"],["EfficientNet-B0 [19]","IQ-OTHNCCD","97.30","0.9850"],["InceptionV3 + GLCM [9]","IQ-OTHNCCD","98.10","0.9910"],["Proposed (AFF + MSCA)","IQ-OTHNCCD","98.36","0.9967"]]}},
    {"id":"lung-table-4","type":"table","data":{"title":"Table IV. C++ edge deployment characteristics","headers":["Metric","Value"],"rows":[["ONNX Model Size","45.3 MB"],["Runtime","ONNX Runtime 1.26.0"],["Compiler","MSVC 19.51 (C++17)"],["Feature Precision Match","< 10^-5 (all 58 features)"],["Prediction Agreement","100% identical to Python"]]}},
    {"id":"lung-8","type":"code","data":{"language":"cpp","code":"string imagePath = \\\"test_ct.png\\\";\\nmean = loadNpyVector(\\\"glcm_lbp_mean.npy\\\");\\nstd_dev = loadNpyVector(\\\"glcm_lbp_std.npy\\\");\\ncout << \\\"Da load thanh cong model.onnx!\\\" << endl;"}},
    {"id":"lung-9","type":"heading","data":{"level":2,"text":"V. CONCLUSION"}},
    {"id":"lung-9b","type":"paragraph","data":{"text":"The final validation story is about consistency: model predictions, heatmaps, and C++ inference output are aligned so the system can be reasoned about as one pipeline rather than a collection of disconnected scripts."}},
    {"id":"lung-10","type":"quote","data":{"text":"The entire pipeline is exported to ONNX format and deployed through a high-performance C++ inference engine using ONNX Runtime and OpenCV.","cite":"Final paper"}}
  ]'::jsonb,
  'published',
  'en',
  9,
  NOW(),
  'Lung Cancer AFF + C++ Inference',
  'Explainable lung cancer classification with feature fusion and edge deployment.'
)
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title,
    excerpt = EXCLUDED.excerpt,
    cover_image_url = EXCLUDED.cover_image_url,
    content_markdown = EXCLUDED.content_markdown,
    content_html = EXCLUDED.content_html,
    content_blocks = EXCLUDED.content_blocks,
    status = EXCLUDED.status,
    language = EXCLUDED.language,
    reading_time_minutes = EXCLUDED.reading_time_minutes,
    published_at = EXCLUDED.published_at,
    seo_title = EXCLUDED.seo_title,
    seo_description = EXCLUDED.seo_description,
    updated_at = NOW();

INSERT INTO blog_tags (slug, name)
VALUES
('portfolio', 'Portfolio'),
('research-notes', 'Research Notes'),
('medical-ai', 'Medical AI'),
('computer-vision', 'Computer Vision'),
('cpp-inference', 'C++ Inference')
ON CONFLICT (slug) DO NOTHING;
